Support PEP517
RDFLib/rdflib-hdt pull request #20
Opened 2023-05-18 10:07 UTC by glaserL

First of all thank you for your package!

# The issue
On PyPi there is no wheel for python 3.10, so pip tries to build from source when i do `pip install rdflib-hdt`, which results in an error, `No module named 'pybind11'`.

<details>
  <summary>Open Full Log</summary>

```
Collecting rdflib-hdt
  Downloading rdflib_hdt-3.0.tar.gz (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.6/235.6 kB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/np/78qcb3_56h7g7tvd3z9vk_1h0000gn/T/pip-install-s2u617xp/rdflib-hdt_30c06c8253134e28b307059c38a61684/setup.py", line 5, in <module>
          import pybind11
      ModuleNotFoundError: No module named 'pybind11'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
</details>

# The solution
The `pyproject.toml` file defines the build requirements for PEP517. Therefore pip (or any other package manager like poetry) installs the build requirements before building itself.

# Test
I tested this by installing from the fork (`pip install git+https://github.com/glaserL/rdflib-hdt`), which works well.

<details>
  <summary>Open Full Log</summary>

```
Collecting git+https://github.com/glaserL/rdflib-hdt
  Cloning https://github.com/glaserL/rdflib-hdt to /private/var/folders/np/78qcb3_56h7g7tvd3z9vk_1h0000gn/T/pip-req-build-dr5jn5ep
  Running command git clone --filter=blob:none --quiet https://github.com/glaserL/rdflib-hdt /private/var/folders/np/78qcb3_56h7g7tvd3z9vk_1h0000gn/T/pip-req-build-dr5jn5ep
  Resolved https://github.com/glaserL/rdflib-hdt to commit 1bee1a766df3ba5e7b5a842c2ab7152bb89a89ce
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pybind11>=2.2.4
  Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
Collecting rdflib>=4.2
  Downloading rdflib-6.3.2-py3-none-any.whl (528 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.1/528.1 kB 1.3 MB/s eta 0:00:00
Collecting pyparsing<4,>=2.1.0
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 1.1 MB/s eta 0:00:00
Collecting isodate<0.7.0,>=0.6.0
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 748.1 kB/s eta 0:00:00
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: rdflib-hdt
  Building wheel for rdflib-hdt (pyproject.toml) ... done
  Created wheel for rdflib-hdt: filename=rdflib_hdt-3.0-cp310-cp310-macosx_10_9_x86_64.whl size=479092 sha256=ba64f58a82da14962560349eefd50581902994b62d214fc55b4c5c1a631596ad
  Stored in directory: /private/var/folders/np/78qcb3_56h7g7tvd3z9vk_1h0000gn/T/pip-ephem-wheel-cache-0s630etk/wheels/f7/b5/68/f1fb13e6fbf1c16d856f6ed7465f80bba03966faa60f0dcbb7
Successfully built rdflib-hdt
Installing collected packages: six, pyparsing, pybind11, isodate, rdflib, rdflib-hdt
Successfully installed isodate-0.6.1 pybind11-2.10.4 pyparsing-3.0.9 rdflib-6.3.2 rdflib-hdt-3.0 six-1.16.0
```
</details>

2023-05-23 14:23 UTC, Callidon requested changes
Thank you for your contribution 👍 Apart from small comment on code cleanup and on a file to delete, it's looking good to me. I've tested an install through pip and it works like a charm 👌

2023-05-23 14:23 UTC, Callidon commented on setup.py
> +from shutil import unpack_archive, move,rmtree
```suggestion
from shutil import unpack_archive, move, rmtree
```

2023-05-23 14:23 UTC, Callidon commented on build-release.sh
You could delete this file, since it's not used by the CD for releases. It's an old file used for manual release in a  dev setup, and it's not relevant anymore.

2023-05-23 17:14 UTC, glaserL commented on setup.py
>      long_description = file.read()
Good catch thank you!

2023-05-23 17:14 UTC, glaserL commented on build-release.sh
Ah thank you, I was unsure if you still use this for something, it's removed

2023-05-23 17:15 UTC, glaserL commented
Thank you very much for your review! 
I updated the PR within the fixup commit, If you are fine with them I will squash them :)

2023-06-02 09:12 UTC, glaserL commented
I'm unsure if I missed a step in the process, can I squash the fixup commit?

2023-06-02 12:02 UTC, Callidon commented
> I'm unsure if I missed a step in the process, can I squash the fixup commit?

Sorry, I was quite busy last weeks, I forgot to reply. I will handle the release, you're PR is good to go, thank you!

2023-06-02 12:17 UTC, Callidon approved these changes

2023-06-02 12:17 UTC, merged

2023-06-02 12:22 UTC, Callidon commented
@glaserL I've released the new version as `v3.1`, can tell me if everything is installing correctly on your side?

2023-06-02 12:31 UTC, glaserL commented
Oh I'm so sorry the fixup commit is still in the history, I am used to get that approved and then everything gets squashed. I hope no one looks into the history.

Works like a charm, thank you very much!

2023-06-02 12:34 UTC, Callidon commented
> Oh I'm so sorry the fixup commit is still in the history, I am used to get that approved and then everything gets squashed. I hope no one looks into the history.

No big deal, I don't think anyone will be annoyed about that 😁 

> Works like a charm, thank you very much!

Great, one good thing done 🚀 Thank you for your contribution 🙏